/**
 * Ingredient → icon-key mapping (O-09). Pure and deterministic. The keys mirror
 * the mobile app's painterly icon set (components/recime/recipes.ts), so a
 * persisted icon resolves to a real asset there. First keyword hit wins; unknown
 * ingredients fall back to `default`.
 */

/** Keyword → icon-key. Order matters: earlier, more specific keys win. Keys must
 * exist in the app's ICON map (components/recime/recipes.ts); unmatched → `default`
 * → the branded Harvest-H fallback. */
const KEYWORDS: Array<[RegExp, string]> = [
  // Grocery-catalog ingredients (specific; placed before the generic recipe
  // matches below so e.g. "cheddar" beats the generic "cheese"). Order within
  // this block also matters: grapefruit before grape, coconut oil before coconut.
  [/apple/, 'apple'],
  [/orange/, 'orange'],
  [/grapefruit/, 'grapefruit'],
  [/grape/, 'grape'],
  [/strawberr/, 'strawberry'],
  [/blueberr/, 'blueberry'],
  [/raspberr/, 'raspberry'],
  [/blackberr/, 'blackberry'],
  [/pineapple/, 'pineapple'],
  [/mango/, 'mango'],
  [/peach/, 'peach'],
  [/pear/, 'pear'],
  [/cherr/, 'cherry'],
  [/watermelon/, 'watermelon'],
  [/cantaloupe|melon/, 'cantaloupe'],
  [/avocado/, 'avocado'],
  [/kiwi/, 'kiwi'],
  [/coconut oil/, 'coconutOil'],
  [/coconut/, 'coconut'],
  [/cranberr/, 'cranberry'],
  [/apricot/, 'apricot'],
  [/\bfig\b/, 'fig'],
  [/\bdates?\b/, 'date'],
  [/raisin/, 'raisin'],
  [/celery/, 'celery'],
  [/cucumber/, 'cucumber'],
  [/zucchini|courgette/, 'zucchini'],
  [/cauliflower/, 'cauliflower'],
  [/napa/, 'cabbageNapa'],
  [/cabbage/, 'cabbage'],
  [/lettuce/, 'lettuce'],
  [/kale/, 'kale'],
  [/\bcorn\b/, 'corn'],
  [/\bpeas?\b/, 'peas'],
  [/green bean/, 'greenBeans'],
  [/asparagus/, 'asparagus'],
  [/eggplant|aubergine/, 'eggplant'],
  [/sweet potato|yam/, 'sweetPotato'],
  [/beet/, 'beet'],
  [/radish/, 'radish'],
  [/squash/, 'squash'],
  [/pumpkin/, 'pumpkin'],
  [/brussels/, 'brusselsSprouts'],
  [/leek/, 'leek'],
  [/okra/, 'okra'],
  [/cilantro|coriander leaf/, 'cilantro'],
  [/\bmint\b/, 'mint'],
  [/rosemary/, 'rosemary'],
  [/\bsage\b/, 'sage'],
  [/\bdill\b/, 'dill'],
  [/arugula|rocket/, 'arugula'],
  [/turkey/, 'turkey'],
  [/lamb/, 'lamb'],
  [/duck/, 'duck'],
  [/sausage/, 'sausage'],
  [/\bham\b/, 'ham'],
  [/crab/, 'crab'],
  [/lobster/, 'lobster'],
  [/scallop/, 'scallop'],
  [/clam/, 'clam'],
  [/mussel/, 'mussel'],
  [/oyster/, 'oyster'],
  [/tuna/, 'tuna'],
  [/salmon/, 'salmon'],
  [/\bcod\b/, 'cod'],
  [/tofu/, 'tofu'],
  [/yogurt|yoghurt/, 'yogurt'],
  [/sour cream/, 'sourCream'],
  [/cream cheese/, 'creamCheese'],
  [/mozzarella/, 'mozzarella'],
  [/cheddar/, 'cheddar'],
  [/parmesan|parmigiano/, 'parmesan'],
  [/\bfeta\b/, 'feta'],
  [/cottage cheese/, 'cottageCheese'],
  [/buttermilk/, 'buttermilk'],
  [/\boats?\b|oatmeal/, 'oats'],
  [/quinoa/, 'quinoa'],
  [/bread ?crumb/, 'breadcrumbs'],
  [/cornmeal|polenta/, 'cornmeal'],
  [/couscous/, 'couscous'],
  [/barley/, 'barley'],
  [/lentil/, 'lentil'],
  [/chickpea|garbanzo/, 'chickpea'],
  [/black bean/, 'blackBeans'],
  [/kidney bean/, 'kidneyBeans'],
  [/pinto bean/, 'pintoBeans'],
  [/peanut/, 'peanut'],
  [/almond/, 'almond'],
  [/cashew/, 'cashew'],
  [/pecan/, 'pecan'],
  [/pistachio/, 'pistachio'],
  [/sunflower seed/, 'sunflowerSeed'],
  [/chia/, 'chiaSeed'],
  [/sesame seed/, 'sesameSeed'],
  [/vegetable oil|canola/, 'vegetableOil'],
  [/vinegar/, 'vinegar'],
  [/ketchup|catsup/, 'ketchup'],
  [/mayo/, 'mayonnaise'],
  // Oils (before generic matches)
  [/olive oil/, 'oliveOil'],
  [/sesame oil/, 'sesameOil'],
  // Stocks (specific beef stock before generic stock/broth)
  [/beef stock|beef broth/, 'beefStock'],
  [/\bstock\b|\bbroth\b/, 'stock'],
  // Proteins (bacon before pork; salmon/fish; shrimp; cheese)
  [/bacon|pancetta/, 'bacon'],
  [/\bpork\b|\bham\b|sausage|chorizo/, 'pork'],
  [/\bbeef\b|brisket|steak|ground beef/, 'beef'],
  [/chicken/, 'chicken'],
  [/salmon|\bfish\b|\bcod\b|tilapia|tuna|haddock/, 'fish'],
  [/shrimp|prawn/, 'shrimp'],
  [/parmesan|mozzarella|cheddar|\bfeta\b|\bcheese\b/, 'cheese'],
  [/\begg/, 'egg'],
  // Produce (scallion before onion; bell pepper before pepper; salt before pepper)
  [/scallion|green onion|spring onion/, 'scallion'],
  [/carrot/, 'carrot'],
  [/\bonion|shallot/, 'onion'],
  [/garlic/, 'garlic'],
  [/ginger/, 'ginger'],
  [/bell pepper|capsicum/, 'bellPepper'],
  [/mushroom/, 'mushroom'],
  [/broccoli/, 'broccoli'],
  [/spinach/, 'spinach'],
  [/potato/, 'potato'],
  [/tomato paste/, 'tomatoPaste'],
  [/tomato/, 'tomato'],
  [/\blime\b/, 'lime'],
  [/lemon/, 'lemon'],
  [/chil(?:i|li|e)|jalapeno|red pepper flake/, 'chili'],
  [/banana/, 'banana'],
  // Seasoning (salt before pepper so "salt and pepper" resolves to salt)
  [/\bsalt\b/, 'salt'],
  [/pepper/, 'pepper'],
  [/paprika/, 'paprika'],
  [/cumin/, 'cumin'],
  [/oregano/, 'oregano'],
  [/thyme/, 'thyme'],
  [/basil/, 'basil'],
  [/parsley|cilantro|coriander/, 'parsley'],
  [/cinnamon/, 'cinnamon'],
  [/vanilla/, 'vanilla'],
  // Pantry / dairy / liquids
  [/soy sauce|\bsoy\b/, 'soySauce'],
  [/mustard/, 'mustard'],
  [/red wine|merlot|pinot/, 'redWine'],
  [/bouillon/, 'bouillon'],
  [/cornstarch|corn starch|cornflour/, 'cornstarch'],
  [/flour/, 'flour'],
  [/brown sugar/, 'brownSugar'],
  [/\bsugar\b/, 'sugar'],
  [/honey/, 'honey'],
  [/butter/, 'butter'],
  [/heavy cream|sour cream|\bcream\b/, 'cream'],
  [/\bmilk\b/, 'milk'],
  [/\brice\b/, 'rice'],
  [/pasta|spaghetti|noodle|penne|macaroni|linguine/, 'pasta'],
  [/baking soda/, 'bakingSoda'],
  [/walnut/, 'walnuts'],
];

/**
 * Map an ingredient line to a painterly icon key.
 *
 * @param name - The ingredient text (any casing; may include quantity).
 * @returns The matching icon key, or `default` when nothing matches.
 */
export function mapIngredientIcon(name: string): string {
  const lower = name.toLowerCase();
  const hit = KEYWORDS.find(([re]) => re.test(lower));
  return hit ? hit[1] : 'default';
}
